/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData accommodation = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData activities = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData articles = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData assistance = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData arrowright = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData clip = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cliped = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cs = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData flight = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData flightfull = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData journey = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData lang = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData logowhite = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData me = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData payment = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData price = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData reminder = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData tours = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData customized = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData destination = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData liked = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData scan = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe822, fontFamily: _kFontFam);
}
